apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mockmetrics-sm
  namespace: monitoring
  labels:
    release: mon
spec:
  jobLabel: mockmetrics
  selector:
    matchLabels:
      app: mockmetrics-app
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: metrics-svc-port
    interval: 10s
    path: /metrics
