apiVersion: v1
kind: Service
metadata:
  name: mockmetrics-service
  namespace: custom-metrics
  labels:
    app: mockmetrics-app
spec:
  ports:
  - name: metrics-svc-port
    port: 80
    targetPort: 8080
  selector:
    app: mockmetrics
