apiVersion: v1
kind: Namespace
metadata:
  name: custom-metrics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: custom-metrics
data:
  adapter-config-data: |
    rules:
    - seriesQuery: '{namespace="default",service="mockmetrics-service"}'
      resources:
        overrides:
          namespace:
            resource: "namespace"
          service:
            resource: "service"
      # name:
      #   matches: "(.*)"
      metricsQuery: 'avg(sum_over_time(total_hit_count{pod=~"mockmetrics-deploy-(.*)"}[2m])) by (service)'
